// ---------------------------------------------------------------------------
// Stock reference data — seed data for the `stocks` Supabase table.
//
// NGX stocks come from the Kobo Terminal /api/ngxdata/stocks endpoint.
// US stocks are the top ~100 tickers by market cap (S&P 500 representatives).
//
// This data is used to seed the DB on first use so that search autocomplete
// works instantly without hitting live APIs.
// ---------------------------------------------------------------------------

export interface SeedStock {
  symbol: string;
  name: string;
  exchange: "ngx" | "us";
  sector: string;
  currency: "NGN" | "USD";
}

// prettier-ignore
export const NGX_STOCKS: SeedStock[] = [
  { symbol: "AIRTELAFRI", name: "Airtel Africa Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
  { symbol: "DANGCEM", name: "Dangote Cement Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "MTNN", name: "MTN Nigeria Communications Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
  { symbol: "ZENITHBANK", name: "Zenith Bank Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "GTCOPLC", name: "Guaranty Trust Holding Company Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "NENERGY", name: "Nigerian Energy Support Company Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "OANDO", name: "Oando Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "ACCESS", name: "Access Holdings Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "FBNH", name: "FBN Holdings Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "UBA", name: "United Bank for Africa Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "ETI", name: "Ecobank Transnational Incorporated", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "WAPCO", name: "Lafarge Africa Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "NESTLE", name: "Nestle Nigeria Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "NB", name: "Nigerian Breweries Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "SEPLAT", name: "Seplat Energy Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "BUACEMENT", name: "BUA Cement Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "BUAFOODS", name: "BUA Foods Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "GEREGU", name: "Geregu Power Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "TRANSPOWER", name: "Transcorp Power Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "TRANSREAD", name: "Transcorp Hotels Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "PRESCO", name: "Presco Plc", exchange: "ngx", sector: "AGRICULTURE", currency: "NGN" },
  { symbol: "OKOMUOIL", name: "Okomu Oil Palm Plc", exchange: "ngx", sector: "AGRICULTURE", currency: "NGN" },
  { symbol: "DANGSUGAR", name: "Dangote Sugar Refinery Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "HONEYWELL", name: "Honeywell Flour Mills Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "CONOIL", name: "Conoil Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "TOTAL", name: "TotalEnergies Marketing Nigeria Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "MRS", name: "MRS Oil Nigeria Plc", exchange: "ngx", sector: "ENERGY", currency: "NGN" },
  { symbol: "SAHCO", name: "Skyway Aviation Handling Company Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "NCR", name: "NCR (Nigeria) Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
  { symbol: "CUTIX", name: "Cutix Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "SUNUASSUR", name: "Sunu Assurances Nigeria Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "LIVINGTRUST", name: "LivingTrust Mortgage Bank Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "VERITASKAP", name: "Veritas Kapital Assurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "CILEASING", name: "C&I Leasing Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "REDSTAREX", name: "Red Star Express Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "NNFM", name: "Northern Nigeria Flour Mills Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "CAVERTON", name: "Caverton Offshore Support Group Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "CNIF", name: "CNI Finance Plc", exchange: "ngx", sector: "CONSTRUCTION/REAL ESTATE", currency: "NGN" },
  { symbol: "RTBRISCOE", name: "RT Briscoe Nigeria Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "MORISON", name: "Morison Industries Plc", exchange: "ngx", sector: "HEALTHCARE", currency: "NGN" },
  { symbol: "REGALINS", name: "Regal Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "ABCTRANS", name: "ABC Transport Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "UNIVINSURE", name: "Universal Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "HMCALL", name: "HMC Alliances Plc", exchange: "ngx", sector: "CONSTRUCTION/REAL ESTATE", currency: "NGN" },
  { symbol: "MULTIVERSE", name: "Multiverse Mining and Exploration Plc", exchange: "ngx", sector: "NATURAL RESOURCES", currency: "NGN" },
  { symbol: "ZICHIS", name: "Zichis Agro Allied Industries Plc", exchange: "ngx", sector: "AGRICULTURE", currency: "NGN" },
  { symbol: "MEYER", name: "Meyer Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "SFSREIT", name: "SFS Real Estate Investment Trust Plc", exchange: "ngx", sector: "CONSTRUCTION/REAL ESTATE", currency: "NGN" },
  { symbol: "LEGENDINT", name: "Legend Internet Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
  { symbol: "LEARNAFRCA", name: "Learn Africa Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "RONCHESS", name: "Ronchess Global Resources Plc", exchange: "ngx", sector: "CONSTRUCTION/REAL ESTATE", currency: "NGN" },
  { symbol: "GOLDBREW", name: "Golden Guinea Breweries Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "ROYALEX", name: "Royal Exchange Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "CHELLARAM", name: "Chellaram Plc", exchange: "ngx", sector: "CONGLOMERATES", currency: "NGN" },
  { symbol: "UNIONDICON", name: "Union Dicon Salt Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "GUINEAINS", name: "Guinea Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "ACADEMY", name: "Academy Press Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "MCNICHOLS", name: "McNichols Consolidated Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "STACO", name: "Staco Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "OMATEK", name: "Omatek Ventures Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
  { symbol: "NSLTECH", name: "NSL Tech Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "AFRINSURE", name: "African Alliance Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "PREMPAINTS", name: "Premier Paints Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "INTENEGINS", name: "International Energy Insurance Plc", exchange: "ngx", sector: "FINANCIAL SERVICES", currency: "NGN" },
  { symbol: "JOHNHOLT", name: "John Holt Plc", exchange: "ngx", sector: "CONGLOMERATES", currency: "NGN" },
  { symbol: "ENAMELWA", name: "Enamelware Nigeria Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "EKOCORP", name: "Eko Corporation Plc", exchange: "ngx", sector: "HEALTHCARE", currency: "NGN" },
  { symbol: "TRIPPLEG", name: "Triple Gee & Company Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "AUSTINLAZ", name: "Austin Laz & Company Plc", exchange: "ngx", sector: "INDUSTRIAL GOODS", currency: "NGN" },
  { symbol: "UPL", name: "Unilag Investments Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "MULTITREX", name: "Multi-Trex Integrated Foods Plc", exchange: "ngx", sector: "CONSUMER GOODS", currency: "NGN" },
  { symbol: "ALEX", name: "Alex Picot (Nigeria) Plc", exchange: "ngx", sector: "NATURAL RESOURCES", currency: "NGN" },
  { symbol: "TRANSEXPR", name: "Trans-Express Nigeria Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "JULI", name: "Juli Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "THOMASWY", name: "Thomas Wyatt Nigeria Plc", exchange: "ngx", sector: "NATURAL RESOURCES", currency: "NGN" },
  { symbol: "AFROMEDIA", name: "Afromedia Plc", exchange: "ngx", sector: "SERVICES", currency: "NGN" },
  { symbol: "PHARMDEKO", name: "Pharma-Deko Plc", exchange: "ngx", sector: "HEALTHCARE", currency: "NGN" },
  { symbol: "BAPLC", name: "Bon Appetit Plc", exchange: "ngx", sector: "ICT", currency: "NGN" },
];

// prettier-ignore
export const US_STOCKS: SeedStock[] = [
  { symbol: "AAPL", name: "Apple Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "MSFT", name: "Microsoft Corporation", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "BRK.A", name: "Berkshire Hathaway Inc. (Class A)", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "LLY", name: "Eli Lilly and Company", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "AVGO", name: "Broadcom Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "V", name: "Visa Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "XOM", name: "Exxon Mobil Corporation", exchange: "us", sector: "Energy", currency: "USD" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "COST", name: "Costco Wholesale Corporation", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "HD", name: "The Home Depot Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "PG", name: "The Procter & Gamble Company", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "us", sector: "Communication Services", currency: "USD" },
  { symbol: "ABBV", name: "AbbVie Inc.", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "CRM", name: "Salesforce Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "BAC", name: "Bank of America Corporation", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "CVX", name: "Chevron Corporation", exchange: "us", sector: "Energy", currency: "USD" },
  { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "KO", name: "The Coca-Cola Company", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "LIN", name: "Linde plc", exchange: "us", sector: "Basic Materials", currency: "USD" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "ORCL", name: "Oracle Corporation", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "WFC", name: "Wells Fargo & Company", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "DIS", name: "The Walt Disney Company", exchange: "us", sector: "Communication Services", currency: "USD" },
  { symbol: "ACN", name: "Accenture plc", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "ADBE", name: "Adobe Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "COP", name: "ConocoPhillips", exchange: "us", sector: "Energy", currency: "USD" },
  { symbol: "TXN", name: "Texas Instruments Incorporated", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "PM", name: "Philip Morris International Inc.", exchange: "us", sector: "Consumer Defensive", currency: "USD" },
  { symbol: "NEE", name: "NextEra Energy Inc.", exchange: "us", sector: "Utilities", currency: "USD" },
  { symbol: "BA", name: "The Boeing Company", exchange: "us", sector: "Industrials", currency: "USD" },
  { symbol: "GE", name: "GE Aerospace", exchange: "us", sector: "Industrials", currency: "USD" },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "us", sector: "Industrials", currency: "USD" },
  { symbol: "RTX", name: "RTX Corporation", exchange: "us", sector: "Industrials", currency: "USD" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "IBM", name: "International Business Machines Corporation", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "QCOM", name: "QUALCOMM Incorporated", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "DHR", name: "Danaher Corporation", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "VZ", name: "Verizon Communications Inc.", exchange: "us", sector: "Communication Services", currency: "USD" },
  { symbol: "INTC", name: "Intel Corporation", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "CMCSA", name: "Comcast Corporation", exchange: "us", sector: "Communication Services", currency: "USD" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "AMAT", name: "Applied Materials Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "HON", name: "Honeywell International Inc.", exchange: "us", sector: "Industrials", currency: "USD" },
  { symbol: "SPGI", name: "S&P Global Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "us", sector: "Healthcare", currency: "USD" },
  { symbol: "NKE", name: "NIKE Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "MU", name: "Micron Technology Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "SHOP", name: "Shopify Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "SNOW", name: "Snowflake Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "COIN", name: "Coinbase Global Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "ARM", name: "Arm Holdings plc", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "LLYVK", name: "Liberty Media Corporation", exchange: "us", sector: "Communication Services", currency: "USD" },
  { symbol: "SQ", name: "Block Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "SNAP", name: "Snap Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "RIVN", name: "Rivian Automotive Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "SOFI", name: "SoFi Technologies Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "HOOD", name: "Robinhood Markets Inc.", exchange: "us", sector: "Financial Services", currency: "USD" },
  { symbol: "ABNB", name: "Airbnb Inc.", exchange: "us", sector: "Consumer Discretionary", currency: "USD" },
  { symbol: "DASH", name: "DoorDash Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "NET", name: "Cloudflare Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "ZS", name: "Zscaler Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "DDOG", name: "Datadog Inc.", exchange: "us", sector: "Technology", currency: "USD" },
  { symbol: "TTD", name: "The Trade Desk Inc.", exchange: "us", sector: "Technology", currency: "USD" },
];

export const ALL_STOCKS: SeedStock[] = [...NGX_STOCKS, ...US_STOCKS];
