import { BackButton } from "./BackButton";

export const metadata = {
  title: "Privacy Policy — FOS·AI",
  description: "How FOS·AI collects, uses, and protects your personal and financial data.",
};

export default function PrivacyPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        background: "var(--bg)",
        color: "var(--text-1)",
        padding: "32px 16px",
      }}
    >
      <div style={{ maxWidth: "680px", margin: "0 auto" }}>
        <BackButton />

        <h1
          style={{
            fontFamily: "var(--font-display-family)",
            fontSize: "1.75rem",
            fontWeight: 700,
            marginBottom: "8px",
          }}
        >
          Privacy Policy
        </h1>
        <p style={{ fontSize: "0.8125rem", color: "var(--text-3)", marginBottom: "32px" }}>
          Last updated: September 9, 2026
        </p>

        <div
          style={{
            borderRadius: "var(--radius)",
            border: "1px solid var(--glass-border)",
            background: "var(--glass-bg)",
            backdropFilter: "blur(20px) saturate(1.3)",
            WebkitBackdropFilter: "blur(20px) saturate(1.3)",
            padding: "32px",
            display: "flex",
            flexDirection: "column",
            gap: "28px",
            fontSize: "0.875rem",
            lineHeight: 1.7,
            color: "var(--text-2)",
          }}
        >
          <Section title="1. Introduction">
            <p>
              FOS·AI (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is a personal finance management application
              that helps you track your financial health, manage investments, and make informed
              financial decisions. This Privacy Policy explains how we collect, use, disclose, and
              safeguard your information when you use our application and related services.
            </p>
            <p>
              By using FOS·AI, you agree to the collection and use of information in accordance
              with this policy. If you do not agree, please discontinue use of the application.
            </p>
          </Section>

          <Section title="2. Information We Collect">
            <h4 style={{ fontWeight: 600, color: "var(--text-1)", marginBottom: "8px" }}>
              2.1 Information You Provide
            </h4>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li><strong style={{ color: "var(--text-1)" }}>Account Information:</strong> Email address, name, and password used to create your account.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Financial Profile:</strong> Income, expenses, assets, debts, investment holdings, savings goals, and risk tolerance data you enter during onboarding and ongoing use.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Transaction Data:</strong> Financial transactions you log through the money manager feature.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Preferences:</strong> Currency, country, employment status, and other profile settings.</li>
            </ul>

            <h4 style={{ fontWeight: 600, color: "var(--text-1)", marginTop: "16px", marginBottom: "8px" }}>
              2.2 Information Collected Automatically
            </h4>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li><strong style={{ color: "var(--text-1)" }}>Usage Data:</strong> Pages visited, features used, timestamps, and interaction patterns within the application.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Device Information:</strong> Browser type, operating system, screen resolution, and device identifiers.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Log Data:</strong> IP address, access times, and error logs for security and debugging purposes.</li>
            </ul>

            <h4 style={{ fontWeight: 600, color: "var(--text-1)", marginTop: "16px", marginBottom: "8px" }}>
              2.3 Third-Party Data
            </h4>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li><strong style={{ color: "var(--text-1)" }}>Market Data:</strong> Stock prices, market indices, and financial data from third-party providers (Finnhub, NGX data sources) used for investment analysis features.</li>
              <li><strong style={{ color: "var(--text-1)" }}>AI Analysis:</strong> Financial insights generated by AI models based on your data. These insights are generated in real-time and are not stored beyond your session.</li>
            </ul>
          </Section>

          <Section title="3. How We Use Your Information">
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li>To provide, maintain, and improve the FOS·AI application and its features.</li>
              <li>To personalize your financial dashboard and provide tailored insights.</li>
              <li>To calculate financial health scores and investment recommendations.</li>
              <li>To authenticate your identity and protect your account from unauthorized access.</li>
              <li>To communicate with you about updates, security alerts, and support.</li>
              <li>To detect and prevent fraud, abuse, and technical issues.</li>
              <li>To comply with legal obligations and enforce our terms of service.</li>
            </ul>
          </Section>

          <Section title="4. Data Storage and Security">
            <p>
              Your data is stored securely using Supabase, a trusted cloud database provider.
              We implement industry-standard security measures including:
            </p>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li>Encryption of data in transit (TLS/SSL) and at rest.</li>
              <li>Row-level security policies ensuring only you can access your data.</li>
              <li>Regular security audits and monitoring.</li>
              <li>Secure authentication with encrypted session tokens.</li>
            </ul>
            <p>
              While we take reasonable precautions, no method of electronic storage is 100% secure.
              We cannot guarantee absolute security of your data.
            </p>
          </Section>

          <Section title="5. Data Sharing and Disclosure">
            <p>
              We do <strong style={{ color: "var(--text-1)" }}>not</strong> sell, trade, or rent your personal or financial data to third parties.
              We may share information only in the following circumstances:
            </p>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li><strong style={{ color: "var(--text-1)" }}>Service Providers:</strong> With trusted third-party services that help us operate the application (hosting, database, AI providers), bound by confidentiality obligations.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Legal Requirements:</strong> When required by law, regulation, or valid legal process.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Safety:</strong> To protect the rights, property, or safety of FOS·AI, our users, or the public.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, with prior notice.</li>
            </ul>
          </Section>

          <Section title="6. AI and Automated Decision-Making">
            <p>
              FOS·AI uses artificial intelligence (Google Gemini) to generate financial insights,
              stock analysis, and health scores. Please note:
            </p>
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li>AI-generated insights are for informational purposes only and do not constitute financial advice.</li>
              <li>Your data is sent to AI providers only when you actively request analysis.</li>
              <li>We do not use your data to train AI models.</li>
              <li>You can delete your data at any time, which will prevent future AI analysis.</li>
            </ul>
          </Section>

          <Section title="7. Your Rights and Choices">
            <ul style={{ paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "4px" }}>
              <li><strong style={{ color: "var(--text-1)" }}>Access:</strong> You can view all your data within the application at any time.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Correction:</strong> You can update your profile and financial data directly in the app.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Deletion:</strong> You can request deletion of your account and all associated data by contacting us.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Export:</strong> You can request a copy of your data in a portable format.</li>
              <li><strong style={{ color: "var(--text-1)" }}>Restriction:</strong> You can limit how your data is processed by adjusting your preferences.</li>
            </ul>
          </Section>

          <Section title="8. Data Retention">
            <p>
              We retain your personal and financial data for as long as your account is active
              or as needed to provide the application. If you delete your account, we will remove
              your data within 30 days, except where retention is required by law or for
              legitimate business purposes (such as fraud prevention).
            </p>
          </Section>

          <Section title="9. Children&apos;s Privacy">
            <p>
              FOS·AI is not intended for users under the age of 18. We do not knowingly collect
              personal information from children. If we become aware that a child has provided
              us with personal data, we will take steps to delete it promptly.
            </p>
          </Section>

          <Section title="10. International Data Transfers">
            <p>
              Your data may be processed in countries other than your own. We ensure that
              appropriate safeguards are in place for international transfers, including
              standard contractual clauses where required by applicable data protection laws.
            </p>
          </Section>

          <Section title="11. Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time. We will notify you of
              significant changes by posting the new policy in the application and updating
              the &quot;Last updated&quot; date. Your continued use of FOS·AI after changes
              constitutes acceptance of the updated policy.
            </p>
          </Section>

          <Section title="12. Contact Us">
            <p>
              If you have questions about this Privacy Policy or wish to exercise your data
              rights, please contact us at:
            </p>
            <p style={{ color: "var(--accent)", fontWeight: 500 }}>
              privacy@fos-ai.app
            </p>
          </Section>
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3
        style={{
          fontFamily: "var(--font-display-family)",
          fontSize: "1rem",
          fontWeight: 600,
          color: "var(--text-1)",
          marginBottom: "12px",
        }}
      >
        {title}
      </h3>
      <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        {children}
      </div>
    </div>
  );
}
