-- Seed complete NGX stock list (from us_stocks.md — 146 stocks)
-- Uses ON CONFLICT DO NOTHING to skip stocks already in the table.
INSERT INTO stocks (symbol, name, exchange, sector, currency) VALUES
  ('ABBEYBANK', 'Abbey Mortgage Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('ABCTRANS', 'ABC Transport', 'ngx', 'SERVICES', 'NGN'),
  ('ACADEMY', 'Academy Press', 'ngx', 'SERVICES', 'NGN'),
  ('ACCESSCORP', 'Access Holdings', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('AFRINSURE', 'African Alliance Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('AFRIPRUD', 'African Prudential', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('AFROMEDIA', 'Afromedia', 'ngx', 'SERVICES', 'NGN'),
  ('AIICO', 'AIICO Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('AIRTELAFRI', 'Airtel Africa', 'ngx', 'ICT', 'NGN'),
  ('ALEX', 'Aluminium Extrusion Industries', 'ngx', 'NATURAL RESOURCES', 'NGN'),
  ('ARADEL', 'Aradel Holdings', 'ngx', 'OIL AND GAS', 'NGN'),
  ('AUSTINLAZ', 'Austin Laz & Company', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('AVACAP', 'AVA Capital', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('AVAIF', 'AVA Infrastructure Fund', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('BAPLC', 'B.A.P.L.C', 'ngx', 'ICT', 'NGN'),
  ('BERGER', 'Berger Paints', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('BETAGLAS', 'Beta Glass Co', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('BUACEMENT', 'BUA Cement', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('BUAFOODS', 'BUA Foods', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('CADBURY', 'Cadbury Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('CAP', 'Chemical and Allied Products', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('CAVERTON', 'Caverton Offshore Support Group', 'ngx', 'SERVICES', 'NGN'),
  ('CHAMPION', 'Champion Breweries', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('CHAMS', 'Chams', 'ngx', 'ICT', 'NGN'),
  ('CHELLARAM', 'Chellarams', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('CILEASING', 'C & I Leasing', 'ngx', 'SERVICES', 'NGN'),
  ('CMFC', 'Coronation Merchant Finance Co.', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('CNIF', 'Cordros Nigerian Infrastructure Fund', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('CONHALLPLC', 'Consolidated Hallmark Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('CONOIL', 'Conoil', 'ngx', 'OIL AND GAS', 'NGN'),
  ('CORNERST', 'Cornerstone Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('CUSTODIAN', 'Custodian Investment', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('CUTIX', 'Cutix', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('CWG', 'CWG Plc', 'ngx', 'ICT', 'NGN'),
  ('DAARCOMM', 'Daar Communications', 'ngx', 'SERVICES', 'NGN'),
  ('DANGCEM', 'Dangote Cement', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('DANGSUGAR', 'Dangote Sugar Refinery', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('EKOCORP', 'Ekocorp', 'ngx', 'HEALTHCARE', 'NGN'),
  ('ELLAHLAKES', 'Ellah Lakes', 'ngx', 'AGRICULTURE', 'NGN'),
  ('ENAMELWA', 'Nigerian Enamelware', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('ETERNA', 'Eterna Plc', 'ngx', 'OIL AND GAS', 'NGN'),
  ('ETI', 'Ecobank Transnational Incorporated', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('ETRANZACT', 'eTranzact International', 'ngx', 'ICT', 'NGN'),
  ('EUNISELL', 'Eunisell Interlinked', 'ngx', 'SERVICES', 'NGN'),
  ('FCMB', 'FCMB Group', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('FIDELITYBK', 'Fidelity Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('FIDSON', 'Fidson Healthcare', 'ngx', 'HEALTHCARE', 'NGN'),
  ('FIRSTHOLDCO', 'FirstHoldCo', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('FTNCOCOA', 'FTN Cocoa Processors', 'ngx', 'AGRICULTURE', 'NGN'),
  ('GEREGU', 'Geregu Power', 'ngx', 'UTILITIES', 'NGN'),
  ('GOLDBREW', 'Golden Guinea Breweries', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('GTCO', 'Guaranty Trust Holding Company', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('GUINEAINS', 'Guinea Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('GUINNESS', 'Guinness Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('HBMNG', 'H&B Mining', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('HMCALL', 'Homecall Fund', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('HONYFLOUR', 'Honeywell Flour Mills', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('IKEJAHOTEL', 'Ikeja Hotel', 'ngx', 'SERVICES', 'NGN'),
  ('IMG', 'Industrial and Medical Gases Nigeria', 'ngx', 'NATURAL RESOURCES', 'NGN'),
  ('INFINITY', 'Infinity Trust Mortgage Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('INTBREW', 'International Breweries', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('INTENEGINS', 'Intenegins', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('JAIZBANK', 'Jaiz Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('JAPAULGOLD', 'Japaul Gold & Ventures', 'ngx', 'OIL AND GAS', 'NGN'),
  ('JBERGER', 'Julius Berger Nigeria', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('JOHNHOLT', 'John Holt', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('JULI', 'Juli Plc', 'ngx', 'SERVICES', 'NGN'),
  ('LASACO', 'Lasaco Assurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('LEARNAFRCA', 'Learn Africa', 'ngx', 'SERVICES', 'NGN'),
  ('LEGENDINT', 'Legend Internet', 'ngx', 'ICT', 'NGN'),
  ('LINKASSURE', 'Linkage Assurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('LIVESTOCK', 'Livestock Feeds', 'ngx', 'AGRICULTURE', 'NGN'),
  ('LIVINGTRUST', 'Living Trust Mortgage Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('MANSARD', 'Axamansard Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('MAYBAKER', 'May & Baker Nigeria', 'ngx', 'HEALTHCARE', 'NGN'),
  ('MBENEFIT', 'Mutual Benefits Assurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('MCNICHOLS', 'McNichols', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('MECURE', 'Mecure Industries', 'ngx', 'HEALTHCARE', 'NGN'),
  ('MEYER', 'Meyer', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('MOFIREIF', 'Meristem Fund', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('MORISON', 'Morison Industries', 'ngx', 'HEALTHCARE', 'NGN'),
  ('MTNN', 'MTN Nigeria Communications', 'ngx', 'ICT', 'NGN'),
  ('MULTITREX', 'Multi-Trex Integrated Foods', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('MULTIVERSE', 'Multiverse Mining and Exploration', 'ngx', 'NATURAL RESOURCES', 'NGN'),
  ('NAHCO', 'Nigerian Aviation Handling Company', 'ngx', 'SERVICES', 'NGN'),
  ('NASCON', 'Nascon Allied Industries', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('NB', 'Nigerian Breweries', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('NCR', 'NCR (Nigeria)', 'ngx', 'ICT', 'NGN'),
  ('NEIMETH', 'Neimeth International Pharmaceuticals', 'ngx', 'HEALTHCARE', 'NGN'),
  ('NEM', 'NEM Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('NESTLE', 'Nestle Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('NGXGROUP', 'Nigerian Exchange Group', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('NIDF', 'Nigeria Infrastructure Debt Fund', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('NNFM', 'Northern Nigeria Flour Mills', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('NPFMCRFBK', 'NPF Microfinance Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('NREIT', 'Nigeria REIT', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('NSLTECH', 'NSL Technologies', 'ngx', 'SERVICES', 'NGN'),
  ('OANDO', 'Oando', 'ngx', 'OIL AND GAS', 'NGN'),
  ('OKOMUOIL', 'Okomu Oil Palm Company', 'ngx', 'AGRICULTURE', 'NGN'),
  ('OMATEK', 'Omatek Ventures', 'ngx', 'ICT', 'NGN'),
  ('PHARMDEKO', 'Pharma-Deko', 'ngx', 'HEALTHCARE', 'NGN'),
  ('PREMPAINTS', 'Premier Paints', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('PRESCO', 'Presco', 'ngx', 'AGRICULTURE', 'NGN'),
  ('PRESTIGE', 'Prestige Assurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('PZ', 'PZ Cussons Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('REDSTAREX', 'Red Star Express', 'ngx', 'SERVICES', 'NGN'),
  ('REGALINS', 'Regency Alliance Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('RONCHESS', 'Ronchess Global Resources', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('ROYALEX', 'Royal Exchange', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('RTBRISCOE', 'R.T. Briscoe Nigeria', 'ngx', 'SERVICES', 'NGN'),
  ('SCOA', 'SCOA Nigeria', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('SEPLAT', 'Seplat Energy', 'ngx', 'OIL AND GAS', 'NGN'),
  ('SFSREIT', 'SFS REIT', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('SKYAVN', 'Skyway Aviation Handling Company', 'ngx', 'SERVICES', 'NGN'),
  ('SOVRENINS', 'Sovereign Trust Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('STACO', 'STACO Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('STANBIC', 'Stanbic IBTC Holdings', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('STERLINGNG', 'Sterling Financial Holdings', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('SUNUASSUR', 'SUNU Assurances Nigeria', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('TANTALIZER', 'Tantalizers', 'ngx', 'SERVICES', 'NGN'),
  ('THOMASWY', 'Thomas Wyatt Nigeria', 'ngx', 'NATURAL RESOURCES', 'NGN'),
  ('TIP', 'The Initiates', 'ngx', 'SERVICES', 'NGN'),
  ('TOTAL', 'TotalEnergies Marketing Nigeria', 'ngx', 'OIL AND GAS', 'NGN'),
  ('TRANSCOHOT', 'Transnational Corporation Hotels', 'ngx', 'SERVICES', 'NGN'),
  ('TRANSCORP', 'Transnational Corporation of Nigeria', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('TRANSEXPR', 'Trans-Nationwide Express', 'ngx', 'SERVICES', 'NGN'),
  ('TRANSPOWER', 'Transcorp Power', 'ngx', 'UTILITIES', 'NGN'),
  ('TRIPPLEG', 'Tripple Gee & Company', 'ngx', 'INDUSTRIAL GOODS', 'NGN'),
  ('UACN', 'UAC of Nigeria', 'ngx', 'CONGLOMERATES', 'NGN'),
  ('UBA', 'United Bank for Africa', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('UCAP', 'United Capital', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('UHOMREIT', 'Union Homes REIT', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('UNILEVER', 'Unilever Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('UNIONDICON', 'Union Dicon Salt', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('UNITYBNK', 'Unity Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('UNIVINSURE', 'Universal Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('UPDC', 'UPDC Plc', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('UPDCREIT', 'UPDC Real Estate Investment Trust', 'ngx', 'CONSTRUCTION/REAL ESTATE', 'NGN'),
  ('UPL', 'University Press', 'ngx', 'SERVICES', 'NGN'),
  ('VERITASKAP', 'Veritas Kapital Assurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('VFDGROUP', 'VFD Group', 'ngx', 'INVESTMENT', 'NGN'),
  ('VITAFOAM', 'Vitafoam Nigeria', 'ngx', 'CONSUMER GOODS', 'NGN'),
  ('WAPIC', 'Wapic Insurance', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('WEMABANK', 'Wema Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('ZENITHBANK', 'Zenith Bank', 'ngx', 'FINANCIAL SERVICES', 'NGN'),
  ('ZICHIS', 'Neuros ZichHis (Agric)', 'ngx', 'AGRICULTURE', 'NGN')
ON CONFLICT (symbol) DO NOTHING;
